// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {govee} from '../models';
import {config} from '../models';
import {ipc} from '../models';
import {fs} from '../models';

export function AllOff():Promise<main.HUDState>;

export function AllOn():Promise<main.HUDState>;

export function AssignSlot(arg1:number,arg2:string):Promise<main.HUDState>;

export function CancelSetup():Promise<void>;

export function CloseConfig():Promise<void>;

export function CommitMappings():Promise<void>;

export function CycleColor(arg1:number):Promise<main.HUDState>;

export function Dancing():Promise<boolean>;

export function Discover():Promise<main.HUDState>;

export function EndWindowDrag():Promise<void>;

export function FillRemaining():Promise<main.HUDState>;

export function GetActivePool():Promise<Array<number>>;

export function GetDevices():Promise<Array<govee.Device>>;

export function GetPaletteIndex():Promise<number>;

export function GetSlots():Promise<Array<main.SlotView>>;

export function GetState():Promise<main.HUDState>;

export function HandleIPC(arg1:string):Promise<void>;

export function HideHUD():Promise<void>;

export function IsSetupOpen():Promise<boolean>;

export function MarkUIReady():Promise<void>;

export function MoveSlot(arg1:number,arg2:number):Promise<main.HUDState>;

export function OpenConfig():Promise<void>;

export function OpenSetup():Promise<void>;

export function PingActivity():Promise<void>;

export function PersistNow():Promise<void>;

export function PingMotion():Promise<void>;

export function Quit():Promise<void>;

export function RemoteCommand(arg1:string):Promise<string>;

export function RenameSlot(arg1:number,arg2:string):Promise<main.HUDState>;

export function SaveMappings(arg1:Array<config.SlotBinding>):Promise<void>;

export function SaveSettings(arg1:main.SettingsView):Promise<void>;

export function ScanLAN():Promise<main.HUDState>;

export function SetBrightness(arg1:number):Promise<void>;

export function SetConfigAPIKey(arg1:string):Promise<void>;

export function SetIPCServer(arg1:ipc.Server):Promise<void>;

export function SetWebAssets(arg1:fs.FS):Promise<void>;

export function SetWebConfig(arg1:string,arg2:string):Promise<main.SettingsView>;

export function SetWebEnabled(arg1:boolean):Promise<main.SettingsView>;

export function ShowHUD():Promise<void>;

export function StartWindowDrag():Promise<void>;

export function ToggleAll():Promise<main.HUDState>;

export function ToggleDance():Promise<main.HUDState>;

export function ToggleGradient():Promise<main.HUDState>;

export function ToggleSlot(arg1:number):Promise<void>;

export function ToggleWindow():Promise<void>;
