// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AllOff() {
  return window['go']['main']['App']['AllOff']();
}

export function AssignSlot(arg1, arg2) {
  return window['go']['main']['App']['AssignSlot'](arg1, arg2);
}

export function CancelSetup() {
  return window['go']['main']['App']['CancelSetup']();
}

export function CloseConfig() {
  return window['go']['main']['App']['CloseConfig']();
}

export function CommitMappings() {
  return window['go']['main']['App']['CommitMappings']();
}

export function CycleColor(arg1) {
  return window['go']['main']['App']['CycleColor'](arg1);
}

export function Dancing() {
  return window['go']['main']['App']['Dancing']();
}

export function Discover() {
  return window['go']['main']['App']['Discover']();
}

export function EndWindowDrag() {
  return window['go']['main']['App']['EndWindowDrag']();
}

export function FillRemaining() {
  return window['go']['main']['App']['FillRemaining']();
}

export function GetActivePool() {
  return window['go']['main']['App']['GetActivePool']();
}

export function GetDevices() {
  return window['go']['main']['App']['GetDevices']();
}

export function GetPaletteIndex() {
  return window['go']['main']['App']['GetPaletteIndex']();
}

export function GetSlots() {
  return window['go']['main']['App']['GetSlots']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function HandleIPC(arg1) {
  return window['go']['main']['App']['HandleIPC'](arg1);
}

export function HideHUD() {
  return window['go']['main']['App']['HideHUD']();
}

export function IsSetupOpen() {
  return window['go']['main']['App']['IsSetupOpen']();
}

export function MarkUIReady() {
  return window['go']['main']['App']['MarkUIReady']();
}

export function MoveSlot(arg1, arg2) {
  return window['go']['main']['App']['MoveSlot'](arg1, arg2);
}

export function OpenConfig() {
  return window['go']['main']['App']['OpenConfig']();
}

export function OpenSetup() {
  return window['go']['main']['App']['OpenSetup']();
}

export function PingActivity() {
  return window['go']['main']['App']['PingActivity']();
}

export function PingMotion() {
  return window['go']['main']['App']['PingMotion']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function SaveMappings(arg1) {
  return window['go']['main']['App']['SaveMappings'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function ScanLAN() {
  return window['go']['main']['App']['ScanLAN']();
}

export function SetBrightness(arg1) {
  return window['go']['main']['App']['SetBrightness'](arg1);
}

export function SetConfigAPIKey(arg1) {
  return window['go']['main']['App']['SetConfigAPIKey'](arg1);
}

export function ShowHUD() {
  return window['go']['main']['App']['ShowHUD']();
}

export function StartWindowDrag() {
  return window['go']['main']['App']['StartWindowDrag']();
}

export function ToggleDance() {
  return window['go']['main']['App']['ToggleDance']();
}

export function ToggleSlot(arg1) {
  return window['go']['main']['App']['ToggleSlot'](arg1);
}

export function ToggleWindow() {
  return window['go']['main']['App']['ToggleWindow']();
}
